apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "products"
  namespace: "default"
  labels:
    app: "products"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "products"
  template:
    metadata:
      labels:
        app: "products"
    spec:
      containers:
      - name: "products"
        image: "knscassandra/apac-fe-demo-products-svc:latest"