apiVersion: v1
kind: Service
metadata:
  name: webstore-ui
spec:
  type: LoadBalancer
  selector:
    app: webstore-ui
  ports:
    - name: http
      port: 9080
      protocol: TCP
      targetPort: 9080